# Generated by Django 4.1.3 on 2023-01-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='about_me',
        ),
    ]
