# Generated by Django 4.1.6 on 2023-04-08 08:57

import base.db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_user_about_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=12)),
                ('expire', models.BooleanField(default=False)),
                ('tried', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            bases=(models.Model, base.db.ExtraModelHelper),
        ),
        migrations.CreateModel(
            name='ServerToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('key', models.CharField(max_length=256)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('token', models.TextField()),
            ],
        ),
    ]
