# Generated by Django 4.1.3 on 2023-01-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0002_employees_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='city',
            field=models.CharField(choices=[('Toshkent', 'Toshkent'), ('Andijon', 'Andijon'), ('Farg`ona', 'Farg`ona'), ('Namangan', 'Namangan'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxandaryo', 'Surxandaryo'), ('Buxoro', 'Buxoro'), ('Samarqand', 'Samarqand'), ('Jizzax', 'Jizzax'), ('Navoiy', 'Navoiy'), ('Sirdaryo', 'Sirdaryo'), ('Xorazm', 'Xorazm')], max_length=125, null=True),
        ),
    ]
