# Generated by Django 4.1.3 on 2023-01-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0003_alter_employees_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
