# Generated by Django 4.1.6 on 2023-04-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0005_alter_employees_ism_familya_alter_employees_lavozimi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bascade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
