# Generated by Django 4.1.6 on 2023-04-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0006_bascade_alter_employees_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCtg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=256)),
                ('ctg', models.CharField(choices=[('Devan', 'Devan'), ('Kravat', 'Kravat'), ('Stol', 'Stol'), ('Stul', 'Stul'), ('Kreslo', 'Kreslo'), ('Osh_hona mebellari', 'Osh_hona mebellari')], max_length=128)),
                ('height', models.CharField(max_length=128)),
                ('width', models.CharField(max_length=128)),
                ('length', models.CharField(max_length=128)),
            ],
        ),
    ]
