# Generated by Django 4.1.3 on 2023-01-09 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='sayt')),
                ('content', models.CharField(max_length=256)),
                ('slug', models.SlugField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('price_type', models.CharField(choices=[('$', '$'), ('Sum', 'Sum'), ('Rub', 'Rub')], max_length=10)),
                ('len', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('is_bed', models.BooleanField(default=False)),
                ('bed_len', models.IntegerField(blank=True, null=True)),
                ('bed_width', models.IntegerField(blank=True, null=True)),
                ('bed_height', models.IntegerField(blank=True, null=True)),
                ('ctg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category')),
            ],
        ),
    ]
