# Generated by Django 4.1.3 on 2023-01-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.IntegerField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='len',
            field=models.IntegerField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.IntegerField(max_length=256, null=True),
        ),
    ]
