# Generated by Django 4.1.6 on 2023-06-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bed_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bed_len',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bed_width',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_bed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='len',
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(default='MDF', max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
