# Generated by Django 4.1.6 on 2023-06-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img1',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
