# Generated by Django 4.1.3 on 2023-01-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_name_user_about_me_user_bio_user_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
